### ISSUE TITLE
Potential issue with img srcset

### ISSUE THREAD

**Issue by marcoscaceres** [WebReflection/hyperHTML#22] opened 2017-03-21 01:45 UTC
Sorry, I've not had time to fully investigate this wanted to file it before I forget:

```JS
const srcset = ["foo.png 200w"]; 
function toImage(srcset, alt) {
  return hyperHTML.wire()
  `<img
      role="button"
      alt="${alt}"
      srcset="${srcset.join(" ")}"
      width="195" height="80"/>`;
}
```

And then attaching that to a section, Chrome says: 

![screenshot 2017-03-21 12 41 24](https://cloud.githubusercontent.com/assets/870154/24129054/1b41c9fe-0e34-11e7-957d-53b0930cd0cd.png)

**Comment by marcoscaceres** [comment] 2017-03-21 01:54
(the double error there is from my own code, which makes multiple calls to `toImage()`... anyway, hopefully enough there to you to investigate... Ps: ❤️ hyperHTML!)

**Comment by WebReflection** [comment] 2017-03-21 08:23
that's a very interesting issue and while I might be able to somehow fix the error, the logic behind `hyperHTML` will always trigger network requests for something that might not exist, which is the temporary attribute placeholder.

I didn't know images would use `srcset` offline too, but I also see that after those errors, everything works as expected and the srcset, once replaced properly, works as usual.

Two possible solutions here:

  1. ignore the error since it's rather a warning but the DOM has no meaning for warnings
  2. create a list of special attributes to replace with dummy attributes, and once parsed the first time, place attributes back again as non dummy.

To be honest I don't like these solutions, and I might place `srcset` under the section caveats describing that the error can be ignored for real-world results or suggesting work arounds.

```js
const srcset = ["foo.png 200w"];
// use this instead
function withSrcset(srcset, alt) {
  var img = toImage(alt);
  img.srcset = srcset.join(" ");
  return img;
}
function toImage(alt) {
  return hyperHTML.wire()
  `<img
      role="button"
      alt="${alt}"
      width="195" height="80"/>`;
}
```

**Comment by WebReflection** [comment] 2017-03-21 10:24
on second thoughts, I believe ignoring that error is better than trying to fix it.

Not only Chrome is the only browser bothering about it, it actually forces the browser to ignore it instead of trying to load from the network the placeholder.

I think this might be described as "_gotcha_" but it'll be a won't fix. What do you think?

**Comment by WebReflection** [comment] 2017-03-21 11:17
FYI https://bugs.chromium.org/p/chromium/issues/detail?id=703588

**Comment by WebReflection** [comment] 2017-03-21 20:52
I've updated the README explaining the issue:
https://github.com/WebReflection/hyperHTML#attributes-resolved-offline-might-show-warnings

I think I'm going to close this as "_won't fix_" for now, because the issue is a console error but not a real bug for `hyperHTML` and the solution is basically not ideal, since the moment I make those two errors disappear is the moent Chrome will try to download something that will cause networks error each time.

I like Chrome for not triggering the network request, compared to what other browsers do without warning about the "bad attribute content", but I don't like Chrome showing two red errors in console, even if the code didn't break, and Chrome did the right thing discarding an invalid network request upfront.

Apologies if not ideal, but I don't have reasonable workarounds for this. 🤷‍♂️

**Closed** 2017-03-22 11:15 UTC
Labels: bug, enhancement
