### ISSUE TITLE
Adopt reuses a tag with different xpath

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#72] opened 2017-07-27 18:42 UTC
After giving a look at your recent examples page, `Hello world & tick`, I tried `adopt` api just to create a more simlar example to React one.

Imagine the following template with `root` tag containing a wired `h1` tag.

```
    <root></root>
    <div id="tick"></div>
```

```
function tick() {

    // const render = hyperHTML.bind(document.getElementById("tick"));
    const render = hyperHTML.adopt(document.getElementById("tick"));

    render`
        <div>
            <h1>Hello, world2!</h1>
            <h2>It is ${new Date().toLocaleTimeString()}.</h2>
        </div>
    `;
}

setInterval(tick, 1000);
```
So we have two `h1` tags in the dom and only the first one is rendered with `adopt` api: I mean `Hello, world2!` is not rendered. With the usual `bind`, commented out, it works as usual.

Really I have no idea if this behaviour is expected.

Live example: https://hyperhtml-jumpstart.now.sh/

**Comment by WebReflection** [comment] 2017-07-27 18:52
Adopt makes very little sense on non forms based pages and it's inevitably limited and/or experimental so while I'll have a look (tomorrow) at your example I strongly suggest to never use adopt when it's not necessary or the container purpose is to show highly dynamic content.

**Comment by WebReflection** [comment] 2017-07-30 18:41
Just going through the code ... why do you do this?
```js
    static renderEmpty(render) {
        render`${hyperHTML.wire(render, ":empty")``}`;
    }
```
Such an overhead to cleanup a node, few alternatives:
```js
    static renderEmpty(render) {
        render``;
        render`${[]}`;
    }
```

About the rest, if you could please provide the minimal amount of noise in a page to understand and reproduce what you think is an issue ... that'd be very appreciated.

As it is, I've no idea what that page should do, and the bug you mentioned is everything but isolated.

thanks for helping me out.

**Comment by WebReflection** [comment] 2017-07-30 18:48
by the way, the purpose of adopting a node is to pick up its content and use the provided template literal as a reference to map what's in there already.

In your example, when you adopt the `<div id="tick"></div>` element this is empty, so adopting it has no meaning whatsoever.

On the other hand, if you had content in that node like the following one:
```html
<div id="tick">
  <div>
    <h1>Hello, world2!</h1>
    <h2>It is 7:45:01 PM.</h2>
  </div>
</div>
```
You'll see that whenever the tick happens and the `adopt` is used you won't lose for a second the content that was already there.

**This is what `adopt` has been created for** so I am closing this bug since it makes no sense to me.

If you think I've missed something please provide a clean example without anything else beside adopt around, and also be sure whatever you are adopting **has** already the content you expect to adopt.

Regards

**Closed by WebReflection** 2017-07-30 18:48 UTC

**Comment by albertosantini** [comment] 2017-07-30 19:37
Last comments make sense. Thanks.
