### ISSUE TITLE
hyperHTML with Custom Element when Javascript is in the <head>

### ISSUE THREAD

**Issue by judge** [WebReflection/hyperHTML#112] opened 2017-09-14 12:27 UTC
We noticed a issue with hyperHTML in Custom Elements in version 1.6.1.
If you load your JavaScript file before your custom element (eg. in the head), and the custom element has a child custom element with attributes/properties, the child custom element's property setter does not get called in that version.

I created 2 fiddles where you can see the problem:

- 1.6.0 (notice that JavaScript loads in the head): https://jsfiddle.net/tamasbiro/tm42LL9v/
- 1.6.1: https://jsfiddle.net/tamasbiro/jtg684vz/

If you change the position of the JavaScript (after the custom element), it works fine.

We also found out that if we revert this change in the latest version (1.7.3), it works as expected.
The corresponding change is in this commit: https://github.com/WebReflection/hyperHTML/commit/10591b8850b21c2f49ecf976313e9ccf8d884ed9

Please notice the ```toLowerCase()``` on the nodeName.

**Comment by judge** [comment] 2017-09-14 13:01
We also found a previous issue in this change: https://github.com/WebReflection/hyperHTML/compare/v1.5.1...v1.5.2
I hope it helps.

**Comment by WebReflection** [comment] 2017-09-14 13:15
I read `working` in both links and I cannot spot any difference.

**Comment by WebReflection** [comment] 2017-09-14 13:18
I also suggest you using just `HyperHTMLElement` so you have `created`, which is a better entry point than `constructor` to initialize custom elements, and you'll have `this.html` instead of the `_render` you are using that re-bind every single time the same context to hyperHTML (redundant/not-needed/etc)

**Comment by judge** [comment] 2017-09-14 13:29
Sorry it seems JSFiddle does not fork external resources, I created a new one (without forking):
https://jsfiddle.net/tamasbiro/jtg684vz/ (this is version 1.6.1)
I'll update the initial issue.

**Comment by WebReflection** [comment] 2017-09-14 13:56
Uhm ... I think I know what's going on.

On regular DOM, imagine an `input` element, the `value` property does not reflect `input.setAttribute('value', 'anything')` ... actually, in the `input` case, you never want to use `setAttribute('value' ...)` and hyperHTML here does something smart: it removes the attribute because it's special, so you can just read or assign `.value = ` directly.

In your custom element you observe attributes that are also in the prototype, but you don't follow same `input.value` convention, as example: you have the setter invoked through the attribute with the same name.

I have to admit this is an unhandled behavior in hyperHTML, and I wonder if HyperHTMLElement suffers the same, however in that case the attribute is set through the getter, so it better represents the observed attribute as native behavior (attributes are always strings) while here you can have inconsistent values, one that could be set always as string through `setAttribute` and one set directly.

Can I ask you how common/frequent is this pattern for you?

**Comment by WebReflection** [comment] 2017-09-14 14:04
actually, never mind, even HyperHTMLElement fails here:
https://jsfiddle.net/b2pdu8w5/

interesting bug, thanks

**Comment by WebReflection** [comment] 2017-09-14 15:22
hey @judge , by any chance you can try out [this version](https://github.com/WebReflection/hyperHTML/blob/211a0be9bf3505edb0fd55c4e33e349680128351/index.js) and tell me if all your issues are gone?

Thank you!

**Comment by judge** [comment] 2017-09-14 16:46
hi @WebReflection , thanks for the quick reply! I just tried it and it does not fixes our issue. :( You can also check the fiddle I created with the version you linked, you'll still see 'cog'.

This is a common pattern in all of our component because we would like to keep attributes and properties in sync. So a developer can use attributes or properties, they'll do the same. Usually we don't reflect back the attributes in the setter, same as the ```input``` element's ```value``` property. If you set value on an input you won't see it as an attribute, but if you set the attribute you can also get the value through the getter.

**Comment by WebReflection** [comment] 2017-09-14 16:52
Well, if you set directly an input value then it won't be in sync with input.getAttribute('value') which is why I've asked. HyperHTMLElement passes through set/getAttribute to have an always on sync value.

Anyway, the version of hyperHTML I've linked here should preserve native custom elements attributes upgrade/callback ... are you sure you're trying that version?

It should leave the attribute there and let the setter do its job the first time

**Comment by judge** [comment] 2017-09-14 17:47
Yes, I can see the attribute on the custom element and its value is fine but the inner component's render is not. This is an updated fiddle with the version you mentioned: https://jsfiddle.net/tamasbiro/1xsgxd2m/

I also checked your fiddle this version it's working indeed, do you have idea what causes mine to fail? I'm not familiar with HyperHTMLElement (yet). :)

**Comment by WebReflection** [comment] 2017-09-14 18:21
Custom Elements are upgraded and notified with different order (attributeChanged before connected). If you miss the right order you could have unexpected behavior defining elements before or after they are on DOM. HyperHTMLElement ensures you setup and render your custom element at the right time. That's the difference. Can't check now your example though , I'm at the airport traveling soon, apologies

**Comment by WebReflection** [comment] 2017-09-15 17:50
this also works for me: https://jsfiddle.net/c0jmjgrz/ no need to use the state. I'm not sure observables might have funny behavior in there ... anyway, this is not anymore an hyperHTML issues since all it does is rendering info, and it does it right.

**Comment by judge** [comment] 2017-09-18 06:55
Sorry to bring this back but there is something really strange going in here. :)

It seems that the setter of the custom element does not get called, even if you change the attribute in the devtools. Could you please this fiddle?

https://jsfiddle.net/tamasbiro/fuvqLmLL/

Its almost the same as yours linked above except that I use a state object in the render and I use the setter to set the state property. This is a common pattern we use in all of our custom elements and it worked properly before. Also if you open up your devtools and change the attribute on the e-icon element the setter does not get called. If I copy the element (in devtools) and paste it again to the DOM, changing the attribute properly calls the setter.

Could you please have a look? Thanks!

**Comment by WebReflection** [comment] 2017-09-18 12:03
Hi @judge, this is a very interesting issue indeed. Basically `hyperHTML` acts before the element gets updated, and this messes up the attribute state once the element is fully updated.

The [last changes I've pushed](https://github.com/WebReflection/hyperHTML/blob/ce715561a10e2623119e0fe5bfc7c583452c2ece/index.js) should solve this issue once for all: it understands special attributes, it doesn't directly assign them until the node is upgraded, in case this is a custom element.

Beside asking you to re-test with latest, I'd like to ask you a question: why do you use this indirect pattern through observed attributes? Wouldn't this pattern make the attribute state itself inconsistent?

What I've realized is that `HyperHTMLElement` class automatically use `setAttribute` and `getAttribute` through observed attributes, using the `attributeChangeCallback` as single source of truth for attribute changes and values.

This means that if you do `el.observed = 123` it will trigger automatically `attributeChangedCallback` after doing simply `el.setAttribute('observed', 123)`.

This means that `el.observed` is always `===` to `el.getAttribute('observed')`, since specifying it in `get observedAttributes[...]` array means I want to use the get/set attribute mechanism, but this is not the pattern you are using. If you directly assign any value to the generic `el`, its state will be inconsistent so that `el.icon` could be `!==` from `el.getAttribute("icon")` and also values set as `el.setAttribute('icon', value)` will always be string, but the `el.icon` wouldn't.

I still think I had to fix upgrades in my code, but I'm also puzzled by this pattern that maybe has secret powers I cannot see. Thanks for any sort of clarification.

**Comment by judge** [comment] 2017-09-19 06:07
Hi @WebReflection,
Yes this version solves our issues, thank you!

About the pattern: the reason we don't use ```setAttribute``` on property changes is that we don't want to reflect every property change to attributes. We have some properties with non string data, we think it's not a great pattern to reflect those to attributes (for example a chart component with a data property which could be a really huge dataset). We do reflect some changes but it's up to the setter if needed. The only important thing for us is to keep attributes sync with properties. If you change a property of a component, you usually don't need the attribute as you already use JavaScript to handle data passing, it's easier and cleaner to use properties. Also if you check native ```input``` element's value property/attribute, its the same pattern.

There is a great talk about this in this video (from the Polymer summit): https://youtu.be/sK1ODp0nDbM?t=14m25s

**Comment by WebReflection** [comment] 2017-09-19 07:18
> if you check native input element's value property/attribute, its the same pattern.

well ... no, it isn't. To start with, `value` attribute is not observed, so it's already very different.

If you set directly `input.value = 123` and you read it back, it will be a string, never something else than a string. If you `input.setAttribute('input', 456)` this won't reflect as value neither ... so I still think your approach with observed attributes is somehow weird but I'm happy this version solved the issue.

**Closed** 2017-09-19 07:19 UTC

**Comment by WebReflection** [comment] 2017-09-19 07:20
P.S. version published as `1.8.0`
