### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'ELEMENT_NODE' in null

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/hyperHTML#243] opened 2018-06-16 13:27 UTC
I get the Following error when reordering an array used to render items:
`Uncaught TypeError: Cannot use 'in' operator to search for 'ELEMENT_NODE' in null`

The weird thing is that it only happens with one set of data but not the other one.

Here is one codepen where it is working: https://codepen.io/jaschaio/pen/gKxeVx

Here is another one where it throws the error: https://codepen.io/jaschaio/pen/MXJzQw

Just try changing the `Order by:` select field.

The only difference is between the two is the array that is used to render the items. The array structure is exactly the same, but one throws said error and I just can't understand where its coming from.

It somehow seems to be caused by using `hyperHTML.wire( this, ':post-' + item.id )` in line 15. If I change it to `hyperHTML.wire( this, ':post-' + index )` no error is thrown. But the index changes depending on how I order the items, so the most performant option should be using `item.id` for the unique ID instead of `index`.

**Comment by WebReflection** [comment] 2018-06-16 16:42
if those items are not exposed, you can use the `index` without any issue, the result is that more items might get those parts updated, but updates are super cheap and fast in hyperHTML.

However, I don't fully understand what's the different between these two demoes, but something tells me you have duplicated IDs in your JSON data so stuff doesn't work as expected.

**Comment by WebReflection** [comment] 2018-06-18 09:43
It looks like you've accidentally discovered a very nasty bug hidden in the domdiff algorithm.

Everything has been fixed now, and tests were added too.

The minimal way to reproduce the issue is through this bug:
https://github.com/WebReflection/domdiff/issues/6#issue-333192475

I'm so happy I've spotted this issue so thank you very much for filing this ticket.

**Comment by WebReflection** [comment] 2018-06-18 14:54
yup, fixed in 2.10.11, sorry for that.

**Closed by WebReflection** 2018-06-18 14:54 UTC

**Comment by jaschaio** [comment] 2018-06-18 16:20
@WebReflection Great to hear that! I was initally refraining from filling this ticket for two days as I thought that it was probably my mistake. Thanks so much for taking another look. Not being able to grasph why it wasn't working was driving me crazy 😂

**Comment by WebReflection** [comment] 2018-06-18 16:43
@jaschaio apologies I didn't have a deeper look initially, so I thought it must've been same ID appended twice, hence some glitch, it turned out to be a very disaster-prone issue with the domdiff algo , happy I've spotted that.

If you write code that makes sense and it doesn't work, please don't hesitate to open bugs.

Thanks.
