### ISSUE TITLE
Unintuitive error message when inserting expression within tags

### ISSUE THREAD

**Issue by saschanaz** [WebReflection/hyperHTML#192] opened 2018-02-10 05:47 UTC
On hyperHTML 2.5.9:

```js
hyperHTML.wire()`<a ${''}></a>`
// TypeError: this[(i - 1)] is not a function
```

I tried using this pattern to conditionally add attributes and got this. ~~I'm not sure it's a supported feature or not,~~ but the result is absolutely unintuitive.

**Edit:** It seems the right way to conditionally add attributes is using `null`/`undefined`.

**Comment by albertosantini** [comment] 2018-02-10 10:23
I know that feeling and about improving the error messages you may give a look at https://github.com/WebReflection/hyperHTML/issues/53#issuecomment-304481706 

(Please, shall you provide a plunker or a codepen reproducing the issue, because it seems in my local examples I cannot replicate it?)

And I suppose you read the issue "Conditional attributes" https://github.com/WebReflection/hyperHTML/issues/87.

**Comment by saschanaz** [comment] 2018-02-10 10:44
https://codepen.io/SaschaNaz/pen/BYWqQj

Ah sorry, I got my codepen here.

**Comment by albertosantini** [comment] 2018-02-10 11:23
I see. Thanks for the repro. 

That is expected.
The result would be `<a ""></a>` and it would not make sense too much from the point a view of a partial: the exception means there is something missing in the template.

See the above suggested issue for solutions about conditional or optional attributes.

**Comment by WebReflection** [comment] 2018-02-10 13:09
>  It seems the right way to conditionally add attributes is using null/undefined.

Yes. When you pass `null` or `undefined` instead of any other value the attribute will be deleted. Similarly you can use `true` or `false` for boolean attributes such `<button disabled=${isDisabled} />` but these will be set directly through the node, not via `setAttribute`

> Unintuitive error message when inserting expression within tags

If it's about the (in)famous `this[i - 1]` error, with hyperHTML the moment you see that is the moment you know your template has something wrong.

The [update](https://github.com/WebReflection/hyperHTML/blob/master/esm/hyper/render.js#L51-L57) function is designed to be the fastest possible JS:
```js
function update() {
  const length = arguments.length;
  for (let i = 1; i < length; i++) {
    this[i - 1](arguments[i]);
  }
}
```
there is no way I can put a try catch in there and show a meaningful error unless I create two versions of the same function, one for debugging and one for production.

However, the rare times it happened to me (it's something everyone at the beginning will crash into then once you get how to write valid HTML with hyperHTML you won't see this error ever again) it was instantly easy to spot my template had errors.

This is a won't fix for now, it might be improved in the future though.

**Closed by WebReflection** 2018-02-10 13:09 UTC
