### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/hyperHTML#53] opened 2017-05-27 22:53 UTC
Not intentionally, I created a "wrong" html template, `render_ko` and I got the following exception:

```
script.js:22 Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at appendNodes (unpkg.com/hyperhtml@0.11.6:284)
    at updateViaArray (unpkg.com/hyperhtml@0.11.6:404)
    at Array.any (unpkg.com/hyperhtml@0.11.6:154)
    at HTMLUnknownElement.update (unpkg.com/hyperhtml@0.11.6:463)
    at HTMLUnknownElement.upgrade (unpkg.com/hyperhtml@0.11.6:487)
    at HTMLUnknownElement.hyperHTML (unpkg.com/hyperhtml@0.11.6:18)
    at script.js:22
```

With the snippet:
```
const state = Introspected({
  toasts: [
    { date: new Date(), message: "now" },
    { date: new Date(), message: "now" }
  ]
});

const render_ko = hyperHTML.bind(document.querySelector("root"));
const render_ok = hyperHTML.bind(document.querySelector("root2"));

render_ok`
    <table>
        <tbody>${
            state.toasts.map(toast => hyperHTML.wire(toast, ":tr")`<tr>
                <td> ${toast.date} </td>
                <td> ${toast.message} </td>
            </tr>`
        )}</tbody>
    </table>
`;

render_ko`
    <table>
        <tbody>
            <tr>${
                state.toasts.map(toast => hyperHTML.wire(toast, ":tr")`
                    <td> ${toast.date} </td>
                    <td> ${toast.message} </td>
                `)}</tr>
        </tbody>
    </table>
`;
```

Live demo: https://plnkr.co/edit/XLjGu9Ag2WldQ0Uf7y93?p=preview

**Comment by WebReflection** [comment] 2017-05-27 22:58
I won't fix wrong templates, it's like a syntax error in JS.

What would you expect instead?

**Comment by WebReflection** [comment] 2017-05-27 23:03
Anyway, I'll see if native template supports multiple <td>. If it does I'd like to know which browser failed and its version / platform too, thanks.

**Comment by WebReflection** [comment] 2017-05-27 23:03
Multiple TDs ... github swallowed that

**Comment by albertosantini** [comment] 2017-05-27 23:19
I would expect a better message error.

If the message doesn't give any insight, that is too much cryptic, the second step is giving a look at the stack trace. It reports the problem at the `render` line, highlighting an issue with the template.

I would like a third step, pointing out the offending part in the template

Maybe I would something on user side like
```
render`...` || console.error("error in template foo"); 
// but this is only a faster method for step one and two
```

My environment is the following:
Chrome Version 58.0.3029.110 (64-bit) - Windows 10 Version 1703 (OS Build 15063.296), Redstone 2.

**Comment by jcmoore** [comment] 2017-05-28 04:44
Just passing by here...

Wondering if the problem is fully understood -- the error is thrown in `appendNodes()` because the (2nd) `childNodes` argument is of "type" `Node[][]` instead of `Node[]` (array of array of nodes instead of just array of nodes).

@albertosantini , assuming it was your intent, (and although I'm still not 100% on the performance implications) you could avoid the error with something like:

```
render_ko`
    <table>
        <tbody>
            <tr>${
                state.toasts.map(toast => hyperHTML.wire(toast, ":tr")`
                    <td> ${toast.date} </td>
                    <td> ${toast.message} </td>
                `).reduce((a, b) => a.push.apply(a, b) ? a : a, [])}</tr>
        </tbody>
    </table>
`;
```

@WebReflection , if it were to become a common pitfall, you could add a check in `appendNodes` like:
```
if (Array.isArray(childNodes[i])) {
  throw new Error('Nested Array "fragments" are not supported -- must flatten list');
}
```
or something.

**Comment by albertosantini** [comment] 2017-05-28 06:51
@jcmoore Thanks for the details. During the debugging, I noticed it.

I would not add that kind of defensive code in the template, because it seems I am fixing an error: it would be better to write correctly the template. :)

I appreciate the minimal approach of the lib and I don't want it includes "checks and controls" to mitigate user errors: anyway the lib throws an exception and it may be enough.

Maybe this issue is only a "rant" and after converting dozens of templates that exception might be fair enough. :)

**Comment by WebReflection** [comment] 2017-05-28 09:43
I've quickly replies from my phone and hadn't got a chance to test the issue but if a template accepts two TDs it looks like a bug indeed and it will be solved. The 'render' tag returns a node or an array of nodes, if you fallback into a string it will use it as HTML but if you throw it'll be a whole new mess. 

I don't want hyperHTML to be too forgiving and surely it won't ever validate templates or goodbye every strong point/achievement of the lib (size and perf).

I will check this issue ASAP though and will fix the bug, if any, or opinions about possible improvements.

**Comment by WebReflection** [comment] 2017-05-28 09:44
Or ask opinions ...geeez this phone

**Comment by WebReflection** [comment] 2017-05-28 11:43
I've had a look, and I'm not sure if this is a bug. You were mapping N TDs instead on N TRs with their 2 TDs content, and it would have produced unexpected results. I actually like the fact you cannot have infinite Arrays in Arrays 'cause you need to know what you're doing.

So, early throw due mistake is good.

Now, if I'll manage to find time to investigate how badly performance would be impacted checking isArray per each possible value and check if each content might be an array too, I'll put the nice error in place.

**Comment by WebReflection** [comment] 2017-05-29 09:39
After better investigation, I'm a bit puzzled about this issue but I've also realized there's no way I can preemptively intercept these errors, ending up penalizing what should be the hot function which is the appendNode one.

If I put a check in there, and this cannot possibly be a `try/catch` or it will degrade performance, I'll do the check for O(n) operations instead of per container.

However, if I do the check before appending I'll need to use both typeof for fast/common cases, and slow down other common cases behind an `isArray` on the first value.

This would, in any case, not solve the problem for every consecutive values, and it will also make the diff-algo useless: what was a mistake would lead to way slower execution for all correct cases.

If you really need arrays of arrays you can simply flat them via `.concat`

```js
const oO = hyperHTML.wire;

const state = ({
  toasts: [
    { date: new Date(), message: "now" },
    { date: new Date(), message: "now" }
  ]
});

const render_ko = hyperHTML.bind(document.querySelector("root"));

render_ko`
  <table>
    <tbody>
      <tr>${
        [].concat.apply([], state.toasts.map(toast => oO(toast, ":tr")`
          <td> ${toast.date} </td>
          <td> ${toast.message} </td>
        `))}</tr>
    </tbody>
  </table>
`;
```

this is rather an emergency solution for what, once again, was a  mistake and not a desired/explicit intent.

If you have better suggestions, I am listening, but I am afraid unless this issue comes up quite often, and after I'll create the better documentation, I'll try to find out the best way to not slow down most common cases.

Apologies if not ideal, I hope you can understand my reasons behind this.

Regards

**Closed by WebReflection** 2017-05-29 09:39 UTC

**Comment by joshgillies** [comment] 2017-05-30 05:41
Thinking over this issue the last few days I'm wondering whether there's a compromise to be made here? If there's a real concern with fixing the error messaging due to a reduction in performance, would it be worth providing a debug build that includes checks for these type of common mistakes? Of course the production build will be stripped of these checks and as a result we get the best of both worlds?

**Comment by WebReflection** [comment] 2017-05-30 08:02
A special build is not a bad idea but it might take some time and I honestly have better things to do here, like fixing Edge quirks and create a proper website with documentation and live examples.

This ticket is about a user/usage mistake and it got caught in a way or another: he re-iterated over the template and realize it was not doing what it was supposed to do.

That makes me feel confident there's sure room for improvements but it wasn't a blocker so ... way low priority right now.

Again, if I see this as common issue, I'll prioritize. Right now, it's good to have this ticket as reference if it happens again.
